const types = {
  COUNT_UP : 'COUNT_UP',
  COUNT_DOWN : 'COUNT_DOWN',
  LOGIN : 'LOGIN_ASYNC',
  LOGOUT : 'LOGOUT',
  INITIAL_PICTURE: 'INITIAL_PICTURE',
  EMPTY_LIST: 'EMPTY_LIST',
  SELECT_PICTURE: 'SELECT_PICTURE',
  UNSELECT_PICTURE: 'UNSELECT_PICTURE',
  MODE_PICTURE: 'MODE_PICTURE',
  SAVE_PICTURES: 'SAVE_PICTURES',
  CHANGE_STATUS:'CHANGE_STATUS',
  SET_DATE : 'SET_DATE',
  SET_TRAVEL_NAME: 'SET_TRAVEL_NAME',
  ADD_MONEY_ITEM:'ADD_MONEY_ITEM'
};

export default types